services:
  fastapi_app:
    build:
      context: .
      dockerfile: prod.Dockerfile
    volumes:
      - .:/usr/src/app
    expose:
      - "8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - fastapi_app

  redis:
    image: redis:latest
    expose:
      - "6379"
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
